coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
    patch:
      default:
        target: 97%  # Require 80% coverage for new code/patches
        threshold: 5%